name: test
on: [push, pull_request]
jobs:
  check:
    strategy:
      matrix:
        type: [Debug, Release]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v11
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: |
          nix-shell --run "set -e;
            mkdir build && cd build
            cmake .. -DCMAKE_BUILD_TYPE=${{ matrix.type }}
            make check
          "
