name: learn-github-actions
on: [push]
jobs:
  make-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v11
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: |
          nix-shell --run "set -e;
            mkdir build && cd build
            cmake .. -DCMAKE_BUILD_TYPE=Debug
            make check
          "
